name: smart_osm_map
description: A plug-and-play OpenStreetMap widget with clustering, image markers, user location, and nearby radius support.
version: 0.0.1
repository: https://github.com/deeps00007/smart_osm_map
homepage: https://github.com/deeps00007/smart_osm_map


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^8.2.2
  flutter_map_marker_cluster: ^8.2.2
  latlong2: ^0.9.0
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
